name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./node-aws-lambda.Dockerfile
          push: true
          tags: iturgeon/hello-world-lambda:node-aws-lambda

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./node-alpine.Dockerfile
          push: true
          tags: iturgeon/hello-world-lambda:node-alpine
